import type { Category } from './types'

// Spanish terms that map an item name to a category, with Rioplatense variants.
export const categoryTerms: Record<Exclude<Category, 'generico'>, string[]> = {
  fruta: [
    'fruta', 'manzana', 'banana', 'platano', 'pera', 'naranja', 'mandarina', 'limon', 'lima',
    'pomelo', 'frutilla', 'fresa', 'frambuesa', 'arandano', 'mora', 'cereza', 'uva', 'kiwi',
    'ananá', 'anana', 'piña', 'mango', 'durazno', 'melocoton', 'damasco', 'ciruela', 'higo',
    'sandia', 'melon', 'palta', 'aguacate', 'granada', 'coco', 'papaya', 'maracuya',
  ],
  verdura: [
    'verdura', 'verduras', 'vegetales', 'hortaliza', 'lechuga', 'rucula', 'espinaca', 'acelga',
    'repollo', 'kale', 'tomate', 'cebolla', 'cebolla de verdeo', 'ajo', 'papa', 'patata',
    'batata', 'boniato', 'zanahoria', 'zapallo', 'calabaza', 'zapallito', 'zucchini', 'calabacin',
    'berenjena', 'morron', 'pimiento', 'aji', 'brocoli', 'coliflor', 'chaucha', 'arveja',
    'choclo', 'pepino', 'apio', 'puerro', 'remolacha', 'rabanito', 'champignon', 'hongo',
    'perejil', 'albahaca', 'cilantro', 'jengibre', 'palmito',
  ],
  carne: [
    'carne', 'carniceria', 'bife', 'asado', 'vacio', 'matambre', 'entraña', 'lomo', 'peceto',
    'nalga', 'cuadril', 'roast beef', 'costilla', 'churrasco', 'milanesa', 'picada', 'carne picada',
    'hamburguesa', 'chorizo', 'morcilla', 'salchicha', 'pancho', 'pollo', 'pechuga', 'pata muslo',
    'suprema', 'cerdo', 'bondiola', 'panceta', 'jamon', 'jamon crudo', 'salame', 'mortadela',
    'fiambre', 'cordero', 'pavita', 'pavo', 'higado', 'achura',
  ],
  pescado: [
    'pescado', 'pescaderia', 'merluza', 'salmon', 'atun', 'trucha', 'lenguado', 'corvina',
    'brotola', 'abadejo', 'sardina', 'anchoa', 'caballa', 'bacalao', 'marisco', 'camaron',
    'langostino', 'mejillon', 'calamar', 'pulpo', 'almeja', 'vieira', 'centolla', 'surimi',
  ],
  lacteos: [
    'lacteo', 'lacteos', 'leche', 'leche descremada', 'yogur', 'yogurt', 'yoghurt', 'queso', 'muzzarella',
    'mozzarella', 'cremoso', 'port salut', 'roquefort', 'parmesano', 'reggianito', 'ricota',
    'queso crema', 'manteca', 'margarina', 'crema', 'crema de leche', 'dulce de leche', 'flan',
    'postre', 'huevo', 'huevos',
  ],
  panaderia: [
    'pan', 'panaderia', 'pan lactal', 'pan rallado', 'baguette', 'flauta', 'felipe', 'mignon',
    'factura', 'medialuna', 'facturas', 'criollito', 'grisin', 'tostada', 'galletita', 'galleta',
    'bizcocho', 'budin', 'torta', 'tarta', 'masa', 'prepizza', 'tapa de empanada', 'tapas',
    'harina', 'levadura', 'brioche', 'churro', 'alfajor', 'donut', 'facturas dulces',
  ],
  bebidas: [
    'bebida', 'agua', 'agua mineral', 'soda', 'gaseosa', 'coca', 'sprite', 'fanta', 'tonica',
    'jugo', 'exprimido', 'cerveza', 'birra', 'vino', 'tinto', 'malbec', 'blanco', 'espumante',
    'champagne', 'fernet', 'gin', 'vodka', 'whisky', 'ron', 'aperitivo', 'vermut', 'licor',
    'cafe', 'te', 'mate', 'yerba', 'yerba mate', 'mate cocido', 'cacao', 'chocolatada',
    'energizante', 'isotonica', 'hielo',
  ],
  almacen: [
    'almacen', 'despensa', 'arroz', 'fideo', 'fideos', 'pasta', 'polenta', 'quinoa', 'lenteja',
    'garbanzo', 'poroto', 'frijol', 'soja', 'avena', 'cereal', 'granola', 'azucar', 'edulcorante',
    'sal', 'pimienta', 'condimento', 'especia', 'oregano', 'comino', 'pimenton', 'aceite',
    'aceite de oliva', 'vinagre', 'mayonesa', 'ketchup', 'mostaza', 'salsa', 'pure de tomate',
    'tomate triturado', 'lata', 'conserva', 'atun en lata', 'arvejas en lata', 'caldo', 'sopa',
    'mermelada', 'miel', 'dulce', 'chocolate', 'golosina', 'caramelo', 'snack', 'papas fritas',
    'mani', 'almendra', 'nuez', 'fruta seca', 'gelatina', 'aceituna',
  ],
  limpieza: [
    'limpieza', 'detergente', 'lavandina', 'cloro', 'jabon en polvo', 'jabon liquido', 'suavizante',
    'desengrasante', 'desinfectante', 'lysoform', 'limpiador', 'limpiavidrios', 'cif', 'ayudin',
    'esponja', 'virulana', 'trapo', 'trapo de piso', 'rejilla', 'secador', 'escoba', 'escobillon',
    'balde', 'guante', 'bolsa de basura', 'bolsa consorcio', 'papel de cocina', 'rollo de cocina',
    'servilleta', 'film', 'papel aluminio', 'lustramuebles', 'quitamanchas', 'destapacañerias',
    'insecticida', 'raid', 'aromatizante', 'desodorante de ambiente',
  ],
  higiene: [
    'higiene', 'jabon', 'shampoo', 'champu', 'acondicionador', 'crema de enjuague', 'gel de ducha',
    'papel higienico', 'toalla', 'toallita', 'pañal', 'pañuelo', 'algodon', 'hisopo', 'cotonete',
    'pasta dental', 'dentifrico', 'cepillo de dientes', 'hilo dental', 'enjuague bucal',
    'desodorante', 'antitranspirante', 'perfume', 'crema', 'crema corporal', 'protector solar',
    'afeitadora', 'gillette', 'espuma de afeitar', 'cera', 'toallitas femeninas', 'tampon',
    'protector diario', 'alcohol en gel', 'barbijo', 'curita', 'alcohol',
  ],
  hogar: [
    'hogar', 'casa', 'lamparita', 'bombita', 'foco', 'led', 'pila', 'bateria', 'vela', 'fosforo',
    'encendedor', 'tornillo', 'clavo', 'martillo', 'destornillador', 'cinta', 'cinta adhesiva',
    'pegamento', 'silicona', 'pintura', 'pincel', 'llave', 'candado', 'percha', 'organizador',
    'almohada', 'sabana', 'acolchado', 'funda', 'cortina', 'alfombra', 'maceta', 'tierra',
    'planta', 'jarron', 'espejo', 'cuadro', 'plato', 'vaso', 'taza', 'cubierto', 'olla',
    'sarten', 'tupper', 'mueble', 'silla', 'mesa', 'estante',
  ],
  ropa: [
    'ropa', 'remera', 'camiseta', 'camisa', 'buzo', 'campera', 'sweater', 'pulover', 'chaleco',
    'pantalon', 'jean', 'jogging', 'short', 'bermuda', 'pollera', 'falda', 'vestido', 'traje',
    'saco', 'medias', 'calcetines', 'ropa interior', 'bombacha', 'calzoncillo', 'boxer',
    'corpiño', 'sosten', 'pijama', 'zapatilla', 'zapato', 'bota', 'ojota', 'sandalia',
    'gorra', 'gorro', 'bufanda', 'guantes', 'cinturon', 'mochila', 'cartera', 'bolso',
  ],
  mascota: [
    'mascota', 'perro', 'gato', 'alimento balanceado', 'balanceado', 'comida para perro',
    'comida para gato', 'pipeta', 'antipulgas', 'collar', 'correa', 'arena para gato',
    'piedritas', 'juguete para perro', 'hueso', 'snack para perro', 'veterinario', 'jaula',
    'pecera', 'alpiste', 'comedero', 'bebedero',
  ],
  tecnologia: [
    'tecnologia', 'cargador', 'cable', 'cable usb', 'usb', 'auricular', 'auriculares', 'parlante',
    'mouse', 'teclado', 'monitor', 'notebook', 'laptop', 'computadora', 'celular', 'telefono',
    'tablet', 'pendrive', 'disco', 'disco externo', 'memoria', 'router', 'modem', 'adaptador',
    'zapatilla electrica', 'enchufe', 'control remoto', 'televisor', 'tele', 'smartwatch',
    'consola', 'joystick', 'impresora', 'tinta', 'toner', 'camara',
  ],
  papeleria: [
    'papeleria', 'papel', 'hoja', 'resma', 'cuaderno', 'anotador', 'agenda', 'libreta',
    'lapiz', 'lapicera', 'birome', 'boligrafo', 'marcador', 'resaltador', 'goma', 'sacapuntas',
    'regla', 'tijera', 'plasticola', 'abrochadora', 'broche', 'clip', 'carpeta', 'folio',
    'sobre', 'estampilla', 'post it', 'pizarra', 'tiza', 'crayon', 'temperas', 'libro', 'revista',
  ],
}
